const config = {
  readonly: false,
  toolbarAdaptive: false,
  buttons: [
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "ul",
    "ol",
    "font",
    "fontsize",
    "lineHeight",
    "superscript",
    "subscript",
    "image",
    "spellcheck",
    "symbols",
    "undo",
    "redo",
    "hr",
    "indent",
    "outdent",
    "left",
    "brush",
    "copy",
    "selectall",
    "paste",
    "find",
    "preview",
    "print",
    "about",
  ],
  placeholder: "想說些什麼...",
};
export default config;
